# https://doc.rust-lang.org/cargo/getting-started/first-steps.html#first-steps-with-cargo
[package]
name = "RuStream"
version = "0.0.1"
description = "Rustic API to stream videos from localhost"
license = "MIT"
documentation = "https://thevickypedia.github.io/rustic-stream"
homepage = "https://github.com/thevickypedia/rustic-stream"
repository = "https://github.com/thevickypedia/rustic-stream"
edition = "2021"

[[bin]]
name = "stream"
path = "src/main.rs"

[dependencies]
actix-rt = "2.9.0"
actix-web = "4.4.1"
serde = "1.0.106"
serde_json = "1.0.51"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.7.0", features = ["serde", "v4"] }
env_logger = "0.11.1"
log = "0.4.20"
