# https://doc.rust-lang.org/cargo/getting-started/first-steps.html#first-steps-with-cargo
[package]
name = "RuStream"
version = "0.0.1-temp"
description = "An API written in Rust, to stream videos using Actix framework, via authenticated sessions"
license = "MIT"
documentation = "https://thevickypedia.github.io/RuStream"
homepage = "https://github.com/thevickypedia/RuStream"
repository = "https://github.com/thevickypedia/RuStream"
edition = "2021"
authors = ["Vignesh Rao"]

[[bin]]
name = "stream"
path = "src/main.rs"

[dependencies]
actix-rt = "2.9.0"
actix-web = "4.5.1"
actix-files = "0.6.5"
actix-cors = "0.7.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
chrono = { version = "0.4.33", features = ["serde"] }
env_logger = "0.11.1"
log = "0.4.20"
lazy_static = "1.4.0"
base64 = "0.21.7"
sha2 = "0.10.8"
rand = "0.8.5"
fernet = "0.2.1"
minijinja = "1.0.12"
pyo3 = { version = "0.20.2", features = ["auto-initialize"] }
url = "2.5.0"
itertools = "0.12.1"
