name: Validate Hyperlinks

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'src/**'
      - 'Cargo.toml'

jobs:
  none-shall-pass:
    runs-on: thevickypedia-lite
    steps:
      - uses: thevickypedia/none-shall-pass@v5
        with:
          excludeHostnames: "crates"
