name: Validate Hyperlinks

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'src/**'
      - 'Cargo.toml'

jobs:
  none-shall-pass:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: thevickypedia/none-shall-pass@v4
        with:
          excludeHostnames: "crates"
