name: Build, Test and Upload Artifact

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  RuStream:
    uses: thevickypedia/rust-releaser/.github/workflows/entrypoint.yml@main
    secrets: inherit
